name: Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "clang17"
            compiler: "clang-17"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "clang16"
            compiler: "clang-16"
            build_type: Release
            cxx_flags: "-std=c++20"

          - name: "clang15"
            compiler: "clang-15"
            build_type: Release
            cxx_flags: "-std=c++20"

          - name: "gcc13"
            compiler: "gcc-13"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc12"
            compiler: "gcc-12"
            build_type: Release
            cxx_flags: "-std=c++20"

          - name: "gcc11"
            compiler: "gcc-11"
            build_type: Release
            cxx_flags: "-std=c++20"

          - name: "IntelLLVM"
            compiler: "intel"
            build_type: Release
            cxx_flags: "-std=c++20 -fp-model=strict"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 125M

      - name: Install dependencies
        run: install libboost-dev libxml2-utils

      - name: Install OpenMP
        if: contains(matrix.name, 'clang')
        env:
          SEQAN_CLANG: ${{ matrix.compiler }}
        run: install libomp-${SEQAN_CLANG:6}-dev

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.27.7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: |
          pip install setuptools wheel
          pip install -r manual/requirements.txt

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }} -Wextra -Wall -pedantic -Werror" \
                   -DSEQAN_DISABLE_VERSION_CHECK=ON \
                   -DSEQAN_GH_ACTIONS_BUILD:BOOL=ON \
                   -DPython3_ROOT_DIR=${pythonLocation} \
                   -DPython3_EXECUTABLE=${pythonLocation}/bin/python3 \
                   -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                   -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build tests
        run: |
          ccache -z
          cd build
          make -k -j2
          ccache -sv

      - name: Run tests
        continue-on-error: true
        id: test
        run: |
          cd build
          ctest . -j2 --output-on-failure --timeout 240

      - name: Rerun failed tests
        if: steps.test.outcome == 'failure'
        run: |
          cd build
          ctest . -j2 --output-on-failure --timeout 240 --rerun-failed
